name: aggregate_root_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "aggregate_root/Gemfile.lock"
      - ".github/workflows/aggregate_root_coverage.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "aggregate_root/Gemfile.lock"
      - ".github/workflows/aggregate_root_coverage.yml"
      - "support/**"
jobs:
  coverage:
    runs-on: self-hosted
    timeout-minutes: 120
    env:
      BUNDLE_GEMFILE: Gemfile
      WORKING_DIRECTORY: aggregate_root
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make install mutate" -E"
             with import <nixpkgs> { };
             mkShell {
               inputsFrom = [
                 (import ../support/nix/ruby_3_1.nix)
               ];
             }
           "
        working-directory: ${{ env.WORKING_DIRECTORY }}
