name: rails_event_store_active_record
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
jobs:
  test:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: rails_event_store_active_record
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATA_TYPE: ${{ matrix.datatype }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: sqlite_3
            datatype: binary
          - ruby: ruby_3_1
            gemfile: Gemfile.rails_6_1
            database: sqlite_3
            datatype: binary
          - ruby: ruby_3_0
            gemfile: Gemfile
            database: sqlite_3
            datatype: binary
          - ruby: ruby_3_0
            gemfile: Gemfile.rails_6_1
            database: sqlite_3
            datatype: binary
          - ruby: ruby_2_7
            gemfile: Gemfile.rails_6_1
            database: sqlite_3
            datatype: binary
          - ruby: ruby_2_7
            gemfile: Gemfile.rails_6_0
            database: sqlite_3
            datatype: binary
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: postgres_12
            datatype: binary
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: postgres_12
            datatype: json
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: postgres_12
            datatype: jsonb
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: postgres_11
            datatype: binary
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: mysql_8_0
            datatype: binary
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: mysql_5_7
            datatype: binary
          - ruby: ruby_2_7
            gemfile: Gemfile
            database: sqlite_3
            datatype: binary
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make install test" -E"
            with import <nixpkgs> { };
            mkShell {
              inputsFrom = [
                (import ../support/nix/${{ matrix.database }}.nix)
                (import ../support/nix/${{ matrix.ruby }}.nix)
              ];
            }
          "
        working-directory: ${{ env.WORKING_DIRECTORY }}
  mutate:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: rails_event_store_active_record
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make install mutate-changes" -E"
             with import <nixpkgs> { };
             mkShell {
               inputsFrom = [
                 (import ../support/nix/ruby_3_1.nix)
               ];
             }
           "
        working-directory: ${{ env.WORKING_DIRECTORY }}
