name: ruby_event_store-protobuf
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-protobuf/**"
      - ".github/workflows/ruby_event_store-protobuf.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-protobuf/**"
      - ".github/workflows/ruby_event_store-protobuf.yml"
      - "support/**"
jobs:
  test:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-protobuf
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby_3_1
            gemfile: Gemfile
            database: sqlite3:db.sqlite3
          - ruby: ruby_3_1
            gemfile: Gemfile.rails_6_1
            database: sqlite3:db.sqlite3
          - ruby: ruby_3_0
            gemfile: Gemfile
            database: sqlite3:db.sqlite3
          - ruby: ruby_3_0
            gemfile: Gemfile.rails_6_1
            database: sqlite3:db.sqlite3
          - ruby: ruby_2_7
            gemfile: Gemfile.rails_6_1
            database: sqlite3:db.sqlite3
          - ruby: ruby_2_7
            gemfile: Gemfile
            database: sqlite3:db.sqlite3
          - ruby: ruby_2_7
            gemfile: Gemfile.rails_6_0
            database: sqlite3:db.sqlite3
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make install test" -E"
            with import <nixpkgs> { };
            mkShell {
              inputsFrom = [
                (import ../../support/nix/${{ matrix.ruby }}.nix)
              ];
            }
          "
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-protobuf
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make install mutate-changes" -E"
             with import <nixpkgs> { };
             mkShell {
               inputsFrom = [
                 (import ../../support/nix/ruby_3_1.nix)
               ];
             }
           "
        working-directory: ${{ env.WORKING_DIRECTORY }}
