name: ruby_event_store-rom_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-rom/Gemfile.lock"
      - ".github/workflows/ruby_event_store-rom_coverage.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-rom/Gemfile.lock"
      - ".github/workflows/ruby_event_store-rom_coverage.yml"
      - "support/**"
jobs:
  mutate:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-rom
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make install mutate" -E"
             with import <nixpkgs> { };
             mkShell {
               inputsFrom = [
                 (import ../../support/nix/ruby_3_1.nix)
               ];
             }
           "
        working-directory: ${{ env.WORKING_DIRECTORY }}
